project_id = "minukuru"

[api]
port = 55321

[db]
port = 55322
shadow_port = 55320

[studio]
port = 55323

[local_smtp]
port = 55324

[analytics]
port = 55327

[functions.content-manifest]
verify_jwt = false

[functions.content-manifest-v2]
verify_jwt = false

[functions.content-review-admin]
verify_jwt = false
